services:
  postgres:
    container_name: postgres_pipeline
    image: postgres:17.4-alpine3.21
    volumes:
      - .local/postgres:/var/lib/postgresql/data/
      - .:/app
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=pipeline
  
 
