services:
  postgres:
    container_name: postgres_pipeline
    image: postgres:14.2-alpine
    volumes:
      - .local/postgres:/var/lib/postgresql/data/
      - .:/app
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pipeline
      - POSTGRES_PASSWORD=pipeline
      - POSTGRES_DB=pipeline
  
 
