[project]
name = "linf-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.13.2"
dependencies = [
    "click>=8.1.8",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "sqlalchemy[mypy]>=2.0.38",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pandas-stubs>=2.2.3.241126",
]
